module.exports.User = require("./user.js")
module.exports.Image = require("./image.js")
module.exports.Service = require("./service.js")
module.exports.Product = require("./product.js")
module.exports.Category = require("./category.js")
module.exports.Post = require("./post.js")